enunciados:
	git web--browse www/index.html

all:
	@echo "Compilacion / ejecucion de la prueba"

cli:
	python3 cli.py
serv:
	python3 serv.py
test:
	python3 -m unittest test.py
clean:
	@echo "Limpiando..."
